### ISSUE TITLE
Pre-commit now throws a warning when targeting a specific branch

### ISSUE THREAD

**Issue by ptrbrynt** [fluttercommunity/import_sorter#45]
**Describe the bug**

When running pre-commit with this config:

```yaml
repos:
  - repo: https://github.com/fluttercommunity/import_sorter
    rev: "master"
    hooks:
      - id: flutter-import-sorter
```

A warning is thrown:

```
[WARNING] The 'rev' field of repo 'https://github.com/fluttercommunity/import_sorter' appears to be a mutable reference (moving tag / branch).  Mutable references are never updated after first install and are not supported.  See https://pre-commit.com/#using-the-latest-version-for-a-repository for more details.
```

**Expected behavior**

I would like a tag to be added to GitHub which I can reference in my pre-commit config.

**Meta Information:**
 - Dart Version: 2.10.5
 - `import_sorter` Version: master
 - Is it a Flutter project? Yes
 - What version of Flutter are you using (if flutter project): 1.22.6
