### ISSUE TITLE
Could not find bin/import_sorter.dart in package import_sorter.

### ISSUE THREAD

**Issue by xinwo** [fluttercommunity/import_sorter#83]
**Describe the bug**
I got
Could not find bin/import_sorter.dart in package import_sorter.
when running 
pre-commit run --all-files
or
flutter pub run import_sorter

But
flutter pub run import_sorter
works just fine

**To Reproduce**
1. added
import_sorter: ^4.6.0
to
pubspec.yaml
dev_dependencies

2. installed pre-commit

3. create .pre-commit-config.yaml as below
```
repos:
  - repo: https://github.com/fluttercommunity/import_sorter
    rev: "master"
    hooks:
      - id: flutter-import-sorter
```

4. run
pre-commit run --all-files
or
flutter pub run import_sorter
gives me 
Could not find bin/import_sorter.dart in package import_sorter.

**Expected behavior**
same result as
flutter pub run import_sorter

**Screenshots**

**Meta Information:**
 - Dart Version: 3.5.4
 - `import_sorter` Version: 4.6.0
 - Is it a Flutter project? yes
 - What version of Flutter are you using (if flutter project): 3.24.5

**Additional context**

**Comment by vkammerer** [comment]
This is something that could be handled by the next maintainer once https://github.com/fluttercommunity/import_sorter/issues/84 is resolved

**Comment by k-kdn-copilot01** [comment]
Consider handling it by myself

```
repos:
  - repo: local
    hooks:
      - id: flutter-import-sorter
        name: Flutter Import Sorter
        entry: dart run import_sorter:main
        language: system
        types: [dart]
        stages: [pre-commit]
```
